# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-12 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='descr',
            new_name='description',
        ),
    ]
