# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0002_auto_20180612_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='description',
            new_name='descr',
        ),
    ]
