# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0003_auto_20180703_1739'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Problem',
            new_name='Plumbing',
        ),
    ]
