# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-22 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0004_auto_20180705_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plumbing',
            name='status',
            field=models.CharField(choices=[('EMERGENCY', 'EMERGENCY'), ('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], default='EMERGENCY', max_length=30),
        ),
    ]
