# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-22 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='status',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
