# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-23 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0003_auto_20180523_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='author',
            field=models.CharField(max_length=5),
        ),
    ]
