# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-11 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0005_auto_20180611_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='author',
            field=models.CharField(max_length=5),
        ),
    ]
