# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-11 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0009_auto_20181011_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='status',
            field=models.CharField(choices=[('!EMERGENCY', 'ASAP'), ('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], default='high', max_length=10),
        ),
    ]
