# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-11 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0011_auto_20181011_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='status',
            field=models.CharField(choices=[('00', '!EMERGENCY'), ('01', 'HIGH'), ('02', 'MEDIUM'), ('03', 'LOW')], default='', max_length=10),
        ),
    ]
