# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-12 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0015_auto_20181012_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='status',
            field=models.CharField(choices=[('0', 'small'), ('1', 'medium'), ('2', 'large'), ('3', 'xlarge')], default='', max_length=10),
        ),
    ]
