# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-12 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0016_auto_20181012_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='status',
            field=models.CharField(choices=[('01', 'EMERGENCY'), ('02', 'HIGH'), ('03', 'MEDIUM'), ('04', 'LOW')], default='', max_length=10),
        ),
    ]
