# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-22 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0023_auto_20181012_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='status',
            field=models.CharField(choices=[('01_EMERGENCY', '!EMERGENCY'), ('02_HIGH', 'HIGH'), ('03_MEDIUM', 'MEDIUM'), ('04_LOW', 'LOW')], default='', max_length=10),
        ),
    ]
