# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-28 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=30)),
                ('descr', models.TextField()),
                ('status', models.CharField(blank=True, default='', max_length=30)),
                ('author', models.CharField(max_length=5)),
            ],
        ),
    ]
