# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-22 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='status',
            field=models.IntegerField(choices=[(1, 'EMERGENCY'), (2, 'High'), (3, 'Medium'), (4, 'Low')], default=1),
        ),
    ]
