# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-22 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_auto_20181022_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='status',
            field=models.CharField(choices=[('EMERGENCY', 'EMERGENCY'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='EMERGENCY', max_length=12),
        ),
    ]
