# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-16 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_auto_20181116_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='status',
            field=models.CharField(choices=[('1_IN_PROGRESS', 'IN PROGRESS'), ('2_cHUJ', 'QUEUE'), ('3_CANCELED', 'CANCELED'), ('4_COMPLETED', 'COMPLETED')], default='2_cHUJ', max_length=30),
        ),
    ]
