# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-12 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric', '0002_auto_20181022_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electric',
            name='status',
            field=models.CharField(choices=[('IN PROGRESS', 'IN PROGRESS'), ('QUEUE', 'QUEUE'), ('CANCELED', 'CANCELED'), ('COMPLETED', 'COMPLETED')], default='QUEUE', max_length=30),
        ),
    ]
