# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-12 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric', '0003_auto_20181112_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='electric',
            name='priority',
            field=models.CharField(choices=[('EMERGENCY', 'EMERGENCY'), ('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], default='EMERGENCY', max_length=30),
        ),
    ]
